env:
  browser: true
  es2021: true
extends:
  - "google"
  - "prettier"
  - "plugin:@typescript-eslint/recommended"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "prettier"
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
root: true
rules:
  no-unused-vars: warn
  "prettier/prettier": "error"
  "arrow-body-style": "off"
  "prefer-arrow-callback": "off"
